test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
cloudinary_dev:
  service: Cloudinary
  folder: images_dev
cloudinary_prod:
  service: Cloudinary
  folder: images

google_dev:
  service: GCS
  project: chicago-bike-dashboard
  credentials: 
  bucket: chicago-bike-dashboard-cbd-images_dev

google_prod:
  service: GCS
  project: chicago-bike-dashboard
  credentials: 
  bucket: chicago-bike-dashboard-cbd-images
